---
version: '3.6'
services:
  streamlit-mlops-drl:
    build:
      context: .
    image: alvarofpp/streamlit-mlops-drl
    command: streamlit run app.py
    container_name: streamlit_mlops_drl
#    network_mode: host
    networks:
      - ppgti
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
#    environment:
#      - DISPLAY=192.168.0.106:0

networks:
  ppgti:
    driver: bridge
