LADDER_MAPS = [
    '16-Bit LE',
    'Abiogenesis LE',
    'Abyssal Reef LE',
    'Acid Plant LE',
    'Acolyte LE',
    'Acropolis LE',
    'Ascension to Aiur LE',
    'Automaton LE',
    'Backwater LE',
    'Battle on the Boardwalk LE',
    "Bel'Shir Vestige LE",
    'Blood Boil LE',
    'Blueshift LE',
    'Cactus Valley LE',
    'Catalyst LE',
    'Cerulean Fall LE',
    'Cyber Forest LE',
    'Darkness Sanctuary LE',
    "Defender's Landing LE",
    'Disco Bloodbath LE',
    'Dreamcatcher LE',
    'Eastwatch LE',
    'Ephemeron LE',
    'Fracture LE',
    'Frost LE',
    'Honorgrounds LE',
    'Interloper LE',
    'Kairos Junction LE',
    "King's Cove LE",
    'Lost and Found LE',
    'Mech Depot LE',
    'Neon Violet Square LE',
    'New Repugnancy LE',
    'Newkirk Precinct TE',
    'Odyssey LE',
    'Paladino Terminal LE',
    'Para Site LE',
    'Port Aleksander LE',
    'Proxima Station LE',
    'Redshift LE',
    'Sequencer LE',
    'Stasis LE',
    'Thunderbird LE',
    'Triton LE',
    "Turbo Cruise '84 LE",
    "Winter's Gate LE",
    'World of Sleepers LE',
    'Year Zero LE',
]

RACES = [
    'Random',
    'Protoss',
    'Human',
    'Zerg',
    'Player',
]

DIFFICULTY = [
    'VeryEasy',
    'Easy',
    'Medium',
    'MediumHard',
    'Hard',
    'Harder',
    'VeryHard',
    'CheatVision',
    'CheatMoney',
    'CheatInsane',
]

PRIORITY = {
    1: 'Normal',
    0: 'Sem prioridade',
    2: 'Prioritário',
}
